### ISSUE TITLE
PR template overview

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#32]
@JDW818 filmed an excellent video on the thinking behind the pull request template used by dbt Labs.  This sounds like a great topic to bring out into the world in devhub!

**Linking all existing resources here:**
- [wistia video](https://getdbt.wistia.com/medias/r3u04isgxf)
- [script](https://docs.google.com/document/d/1NoAflCxcAXpdNLnV_n0O_oCctrhMXoGpcnSun6oAOSY/edit?usp=sharing)

**Comment by krevitt** [comment]
@JDW818 Coap recommended we turn your PR template overview video into a blog post for devhub - honestly I think your script works pretty much as-is as a blog post, but I'll ping you [in the draft](https://docs.google.com/document/d/1NHQ7fSmzJFz_TEGO6zR3YEeoY11mxMYJpPpCN71jtMM/edit#) with a couple things that'd be helpful to finish it up.  

think this one should just be your byline vs me or Ganz, since we won't be doing much writing on it.

**Comment by krevitt** [comment]
Think the only things we need to get this post ready are the screenshots of the DA screenshot + model validation from the [example PR](https://github.com/NaturalRetreats/fishtown-dbt/pull/11) that you walked through.

**Comment by JDW818** [comment]
@krevitt this is awesome! here are the screenshots. let me know what else you need from my end!

<img width="1395" alt="Screen Shot 2021-11-18 at 9 35 25 AM" src="https://user-images.githubusercontent.com/8891740/142446368-1503d2ef-501a-4064-abde-9cd9a2e2213e.png">
<img width="1461" alt="Screen Shot 2021-11-18 at 9 34 59 AM" src="https://user-images.githubusercontent.com/8891740/142446378-1d7a5611-ee7b-4b36-86f5-95bbf3cdf13b.png">

**Comment by krevitt** [comment]
Awesome thanks Jess, feel free to [give the final draft](https://docs.google.com/document/d/1NHQ7fSmzJFz_TEGO6zR3YEeoY11mxMYJpPpCN71jtMM/edit#) a review when you have a few mins (it's transposed almost exactly from the script, but just in case other topics to cover come to mind).

**Comment by JDW818** [comment]
Thumbs up from me!
