### ISSUE TITLE
dbt preferred deployment commands

### ISSUE THREAD

**Issue by coapacetic** [dbt-labs/dbt-technical-blog-writing#33]
@aescay filmed an excellent video on the rationale behind the dbt Labs' preferred deployment commands.  Let's turnkey this into some excellent devhub content:

resources:
- [wistia video](https://getdbt.wistia.com/medias/7em2tj62yo)
- [script](https://docs.google.com/document/d/1RMIQx9ZtSPym7EY0obyXZs_9sxwRQR8bqL4QmDNa5xY/edit?usp=sharing)

**Comment by krevitt** [comment]
@aescay Jason and I put together a draft post based your training video script - think this one should be your byline since we didn't do much writing here.  

[draft is here](https://docs.google.com/document/d/1cO_YDck0tmkrbHjPQA3u8OpcGVpk05MncYcR-NuTezY/edit#) - want to take a run through it and leave any notes you'd like to include?  there are a couple comments there that could use your perspective.

**Comment by krevitt** [comment]
FYI this is ready in [deploy preview here](https://deploy-preview-808--docs-getdbt-com.netlify.app/blog/dbt-production-commands), holler if [in the draft](https://docs.google.com/document/d/1cO_YDck0tmkrbHjPQA3u8OpcGVpk05MncYcR-NuTezY/edit#) if we want any final edits
