### ISSUE TITLE
[NEW] dbt: YAML & Doc Blocks in Seconds

### ISSUE THREAD

**Issue by HassanAlRabea** [dbt-labs/dbt-technical-blog-writing#47]
**What's your key point?**
Stay true to best practices: produce yaml files & mds for source tables without add-ons quickly.

**Link to notes / draft:**
[Google docs link](https://docs.google.com/document/d/195LrIEUvg8G0yqBCeUeV1dvaU4emSgbZ5LNj-C2zekU/edit?usp=sharing)

**Comment by krevitt** [comment]
@HassanAlRabea thanks for opening this!  

couple questions off the top: 

1) curious why using one of those packages is an unattractive option?  have found people getting a lot of traction with those.  

one approach to this subject might be to try out all 3 methods side-by-side (your approach vs the packages) for a bit of a bakeoff, so that people can understand which option is best for them.  

2) I assume this approach is relatively snowflake-specific, but could it also be adapted for bigquery (via similar schema tables) and other warehouses?

**Comment by gwenwindflower** [comment]
seems like this one went cold, closing
